### ISSUE TITLE
faust.Record isodates argument doesn't work in 1.0.16

### ISSUE THREAD

**Issue by vineetgoel** [robinhood/faust#114]
Getting the following error with varys code upon upgrading from faust 1.0.11 to faust 1.0.16:

```
Traceback (most recent call last):
  File "examples/psql.py", line 7, in <module>
    from varys.shovels.psql import PSQLShovel
  File "/Users/vineet/.virtualenvs/varys/lib/python3.6/site-packages/varys/shovels/psql/__init__.py", line 1, in <module>
    from .shovel import PSQLShovel, PSQLTask
  File "/Users/vineet/.virtualenvs/varys/lib/python3.6/site-packages/varys/shovels/psql/shovel.py", line 94, in <module>
    class PSQLTask(Task, isodates=True):
TypeError: __new__() got an unexpected keyword argument 'isodates'
```
