### ISSUE TITLE
problem with python3.6

### ISSUE THREAD

**Issue by santosh1432007** [robinhood/faust#152]
Hello there,
I am trying to use faust for one of my learning project where I am working with GDAL which is compatible up to python3.6 and I find difficulty working with faust 1.0.30 on python3.6 virtual environment. Here is the error I am getting:
 
File "/home/santosh/project/pinp/env3.6/lib/python3.6/site-packages/faust/streams.py", line 58, in <module>
    from contextvars import ContextVar
ModuleNotFoundError: No module named 'contextvars'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello_world.py", line 2, in <module>
    app = faust.App(
  File "/home/santosh/project/pinp/env3.6/lib/python3.6/site-packages/faust/__init__.py", line 229, in __getattr__
    object_origins[name], None, None, [name])
  File "/home/santosh/project/pinp/env3.6/lib/python3.6/site-packages/faust/app/__init__.py", line 1, in <module>
    from .base import App
  File "/home/santosh/project/pinp/env3.6/lib/python3.6/site-packages/faust/app/base.py", line 51, in <module>
    from faust.channels import Channel, ChannelT
  File "/home/santosh/project/pinp/env3.6/lib/python3.6/site-packages/faust/channels.py", line 27, in <module>
    from .streams import current_event
  File "/home/santosh/project/pinp/env3.6/lib/python3.6/site-packages/faust/streams.py", line 63, in <module>
    from aiocontextvars import ContextVar, Context
ModuleNotFoundError: No module named 'aiocontextvars'

Could you please let me know how to fix this issue. Thanks in advance!

**Comment by florimondmanca** [comment]
Same issue here. Also experiencing under Python3.7.

**Comment by santosh1432007** [comment]
@florimondmanca For me with pyhthon3.7 it works fine with v1.0.30. As you tried v1.0.29, could you please confirm me which version of python it works? Is it working on python 3.7 or 3.6? Thanks.

**Comment by florimondmanca** [comment]
@santosh1432007 I tested v1.0.29 with python3.7.

That said, I retried with v1.0.30 to grab the stack trace, but interestingly enough I don't get the error about aiocontextvars anymore... So it seems to work fine on Python 3.7. :+1: Really not sure why I had the author's error earlier!

I was, however, able to reproduce the issue under Python3.6 + v1.0.30.

**Comment by emirot** [comment]
Same here worked using python 3.7.0 instead  of 3.6

**Comment by ask** [comment]
How are you installing Faust?

Yes! Faust requires aiocontextvars on Python 3.6.x, but is in setup.py already:

https://github.com/robinhood/faust/blob/3ac4f2e71e9fcf3d2e21caf5e45fcf15a481641b/setup.py#L112-L113

If you're not using pip/setup.py install, you can install the py36 requirements by doing:

```
$ pip install -U -r requirements/py36.txty
```

**Comment by ask** [comment]
Also looks like `aiocontextvars` changed API recently, so it must depend on `<0.2`

**Comment by DeoLeung** [comment]
need to use `<0.2` otherwise ran into `AttributeError: type object 'Context' has no attribute 'current'` on `python3.6`

**Comment by ask** [comment]
I think this should be fixed in 1.3.0.

We now use the new `setuptools` requirements specifier (`aiocontextvars; python_version<'3.7'`), and also works with the changes in aiocontextvars 0.2

**Comment by Magical-Chicken** [comment]
Just updated to faust 1.3.0, it resolves the issue for me, was able to run faust applications without needing to specify `aiocontextvars==1.2.1` in the reqs. Thanks for taking care of this @ask
